### ISSUE TITLE
[BUG]SpawnCluster error

### ISSUE THREAD

**Issue by kkevinm** [JackTheSpades/SpriteToolSuperDelux#109]
Spawning a cluster sprite with the SpawnCluster macro from _header.asm doesn't work properly. The SpawnClusterGeneric routine expects the original position to be at $02-$04, but the _header macro uses SetupCoords which loads the position at $04-$06. Additionally, I think the sprite number to spawn will be clobbered as the _header routine does xba to backup the value, but then doesn't xba before calling SpawnClusterGeneric (I guess this is also an issue for the other spawn routines). This doesn't appear to be an issue with the released version as that was missing the XBA at the start of SpawnClusterGeneric.
Additionally it would be nice if on finding a cluster slot the routine could also set $18B8 to 1, as otherwise the cluster sprite code doesn't even run.

**Comment by Atari2** [comment]
Upon further inspection it looks like there are a lot of problems with how _header.asm is setup in the various folders.
There's an _header.asm in every sprite type folder and all of them have SpawnSmoke/SpawnExtended/SpawnCluster but their own SetupCoords e.g. this is extended/_header.asm

https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/19d4d1442e25c58f49e7c7698b62c70a3ebb6dbe/extended/_header.asm#L23-L32

And I'm 99% sure this causes all the below routines to use the wrong things:
https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/19d4d1442e25c58f49e7c7698b62c70a3ebb6dbe/extended/_header.asm#L46-L50

Because this will cause SpawnCluster to use the extended positions
