### ISSUE TITLE
Is it possible to support MacOS?

### ISSUE THREAD

**Issue by koba-e964** [JackTheSpades/SpriteToolSuperDelux#57]
I found that in MacOS, we can build this project with slight modifications:
- Apply the following change to `Makefile`:
```
$ git diff
diff --git a/Makefile b/Makefile
index bfd2b28..ef850b0 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CXXFLAGS += -std=c++17 -Wl,--gc-sections -ffunction-sections -fdata-sections
+CXXFLAGS += -std=c++17 -W -ffunction-sections -fdata-sections
 CXXFLAGS += -s -O2 -Wall -std=c++17 -Wno-format
 LDFLAGS += -ldl
 
```
- Download libasar.dylib from https://random.muncher.se/ftp/asar/osx/gcc/ and place it in the project's root directory
  - Without this, `./pixi` stops with the following error messages:
```
dlopen(./libasar.dylib, 1): image not found
dlopen(libasar, 1): image not found
Error: Asar library is missing or couldn't be initialized, please redownload the tool or add the dll.

```

So the question is, is it a possible way to go that this project supports MacOS (and possibly Linux, because for Linux [libasar.so](https://random.muncher.se/ftp/asar/linux/ ) is provided)?
If it is, I think I can make a pull request for supporting these operating systems.

**Comment by Atari2** [comment]
Please don't use the Makefile to build this project, use CMake.
This project already supports linux.
You just have to build the asar's dynamic library yourself.

As for MacOS, I made some changes to the CMakeLists.txt and added a [CI macos runner](https://github.com/JackTheSpades/SpriteToolSuperDelux/runs/4782272487?check_suite_focus=true) to make sure I don't break anything since I don't have a MacOS machine I can test on.

You still have to build asar's dynamic library yourself thought. But pixi itself compiles just fine.
