### ISSUE TITLE
PIXI doesn't resolve where the list is predictably when ROM is on another drive.

### ISSUE THREAD

**Issue by AmperSam-git** [JackTheSpades/SpriteToolSuperDelux#93]
> The following was performed with a clean rom and a clean download of PIXI 1.40

When the rom is on _another drive_ (in my case `S:\\` vs `C:\\`) PIXI uses a path relative to the executable to resolve where the list is and succeeds in finding it when list.txt is in the same folder as the executable:

![image](https://github.com/JackTheSpades/SpriteToolSuperDelux/assets/81581391/c57b5cba-6629-4fcf-b914-af9f8229c56c)

However, when the rom is _on the same drive_ it tries to resolve where the list is _relative to the rom_ instead of the PIXI executable and fails:

![image](https://github.com/JackTheSpades/SpriteToolSuperDelux/assets/81581391/5430ade1-1ecf-4d19-a7bd-b3e5d6a6b97c)

This means you could ostensibly need two copies of the list.txt where the executable is and where the ROM is if you're doing any sort of automated actions.

For context, this issue came up during development of an updated RHR baserom where the build tool was doing some temporary actions in Windows %TEMP% directory, where a copy of the rom is in temp before being transferred back to the project directory and PIXI fails in this context for the reason illustrated above.

I'm not sure what the solution to this problem would be aside from always trying to resolve relative to the executable as that seems the most predictable (and how the other commonly used hacking tools seem to do it) at least in my limited view of how/why PIXI has this behaviour.

**Comment by Atari2** [comment]
The solution to this problem is probably to use the `-l <list>` command line option so you don't have to rely on pixi's path resolution attempts

**Comment by Atari2** [comment]
For clarification, PIXI tries to resolve the list's relative path to the ROM, not the executable, and I don't know what the reason is exactly but I don't really feel good about changing this behavior now since I'm afraid about people relying to it for some reason and breaking backwards compatibility

**Comment by Underrout** [comment]
The [line here](https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/7b75ed9f9c7e5dfb34f01535aa285f1e5ec86d6d/src/paths.cpp#L18) makes `absBasePath` be `""` when the PIXI executable and the ROM are on different drives. That results in `newPath` being just the relative path that was passed with `-l`, which I assume is then resolved relative to the executable rather than the ROM.

Proposal: Allow resolving the list file relative to the executable instead of the ROM with a command line flag that overrides the default behavior. That way it stays backwards compatible while allowing sane resolving as well.

**Comment by Atari2** [comment]
Adding a command line flag is always a possibility (albeit Pixi is becoming a command line flag monster but who cares),
> The [line here](https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/7b75ed9f9c7e5dfb34f01535aa285f1e5ec86d6d/src/paths.cpp#L18) makes absBasePath be "" when the PIXI executable and the ROM are on different drive 

Yes, this is because when on windows when 2 paths are on different drives they can't be relative to each other in any way. In fact, in Python for example, [os.path.relpath](https://docs.python.org/3/library/os.path.html#os.path.relpath) raises an exception when paths pertaining to different drives are passed. 

The "fix" in this case, would be just to detect if the paths are on different drives and just return the absolute path in that case
